import React from 'react';

const sampleUsers = [
    {
        id: 1,
        firstname: 'Pregnant',
        middlename: 'J',
        lastname: 'Joe',
        dob: '1990-01-01',
        gender: 'woman',
        country: 'unitedstates',
        email: 'pregnant.joe@example.com',
        phone: '1234567890',
        username: 'pregnant',
        password: 'L%KF(*$mdf92',
        role: 'pregnantuser',
        weeksPregnant: 5,
        profession: null,
        licenseNumber: null,
        inviteCode: 'invitecode1',
        connections: ['dietitianuser', 'doctoruser'],
        circles: [],
    },
    {
        id: 2,
        firstname: 'Doctor',
        middlename: 'B.',
        lastname: 'Smith',
        dob: '1992-02-02',
        gender: 'intersex',
        country: 'unitedstates',
        email: 'doctor.smith@example.com',
        phone: '2345678901',
        username: 'doctor',
        password: 'kdf?34%$aKS$',
        role: 'provider',
        weeksPregnant: null,
        profession: 'physician',
        licenseNumber: '123',
        inviteCode: 'invitecode2',
        connections: ['pregnantuser', 'dietitianuser', 'nurseuser'],
        circles: [],
    },
    {
        id: 3,
        firstname: 'Dietitian',
        middlename: 'C.',
        lastname: 'Johnson',
        dob: '1994-03-03',
        gender: 'woman',
        country: 'unitedstates',
        email: 'dietitian.johnson@example.com',
        phone: '3456789012',
        username: 'dietitian',
        password: 'p33?P9O#@)*',
        role: 'provider',
        weeksPregnant: null,
        profession: 'dietitian',
        licenseNumber: '321',
        inviteCode: 'invitecode3',
        connections: ['doctoruser', 'pregnantuser'],
        circles: [],
    },

    {
        id: 3,
        firstname: 'Nurse',
        middlename: 'C.',
        lastname: 'Apple',
        dob: '1993-03-03',
        gender: 'woman',
        country: 'unitedstates',
        email: 'nurse.apple@example.com',
        phone: '1001001000',
        username: 'dietitian',
        password: 'lag78@#M0$$',
        role: 'provider',
        weeksPregnant: null,
        profession: 'nurse',
        licenseNumber: '000',
        inviteCode: 'invitecode4',
        connections: ['doctoruser'],
        circles: [],
    }



];

export default sampleUsers;
